name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.22
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  # Use the latest version here

flutter_icons:
  android: true
  ios: true
  image_path: assets/ai.jpg

flutter:
  uses-material-design: true
  assets:
    - images/crash.webp
    - images/bac.webp
    - images/rol.jpg
    - images/proc.gif
    - videos/crash.mp4
